### ISSUE TITLE
[neo_simulation2] MP400 simulation - bot only goes in one direction in neo_track1

### ISSUE THREAD

**Issue by VineetTambe** [neobotix/neo_simulation2#67] opened 2023-04-14 23:56 UTC
Hey,

I am trying to use a custom map for robot simulation. However when I run the simulation and give goal through rviz - the bot can only go forwards and does not rotate/turn to go to goals that are behind the robot.

The same behavior was observed when I run the simulation with the ```MAP_NAME=neo_track1```.
Everything runs smoothly if I use the mpo_700 on my custom map or neo_track1.
I validated this by cloning and setting up the entire simulation repos again.

Is there anything that I am doing wrong?
Any help would be greatly appreciated.

**Comment by padhupradheep** [comment] 2023-04-15 01:36
Possibly related to #66 .. 

Changing to neo_local_planner would be the easiest solution, like I updated earlier today for neo_mp_500 in the previous commit. 

Will fix it soon

**Comment by VineetTambe** [comment] 2023-04-15 02:47
Update: managed to fix it - 
the controller subsection in the navigation.yaml used the regulated pure pursuit controller instead of neo_local_planner and setting ```differential_drive = true``` fixed the issue.

**Comment by padhupradheep** [comment] 2023-04-16 12:44
Cool, you can always use the controller parameters deployed on the real robot.. https://github.com/neobotix/neo_mp_400-2/blob/rolling/configs/navigation/navigation.yaml

**Comment by padhupradheep** [comment] 2023-04-16 12:45
If you are interested you can leave a PR with the fixed parameters for RPP... I'll be happy to review it..

**Comment by padhupradheep** [comment] 2023-04-16 12:47
Duplicate of #66 .. closing it.. 

But @VineetTambe feel free to continue commenting on the thread

**Closed as completed by padhupradheep** 2023-04-16 12:47 UTC
